# Generated by Django 5.0 on 2023-12-18 15:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='BookCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Book Condition',
                'verbose_name_plural': 'Book Conditions',
            },
        ),
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Book Language',
                'verbose_name_plural': 'Book Languages',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('book_isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('wroted_type', models.CharField(max_length=50, verbose_name='Wroted Type')),
                ('page_count', models.IntegerField(verbose_name='Page Count')),
                ('size', models.CharField(max_length=50, verbose_name='Size')),
                ('book_created_at', models.DateTimeField(verbose_name='Book Created At')),
                ('starts', models.IntegerField(verbose_name='Starts')),
                ('description', models.TextField(verbose_name='Description')),
                ('cash_status', models.BooleanField(default=True, verbose_name='Cash Status')),
                ('readed_count', models.IntegerField(default=0, verbose_name='Readed Count')),
                ('reding_count', models.IntegerField(default=0, verbose_name='Red   ing Count')),
                ('want_read_count', models.IntegerField(default=0, verbose_name='Want Read Count')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('real_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Real Price')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Discount')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.author', verbose_name='Author')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.bookcondition', verbose_name='Condition')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.booklanguage', verbose_name='Language')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.category', verbose_name='Category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.publisher', verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/', verbose_name='Image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Is Main')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_images', to='book.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Book Image',
                'verbose_name_plural': 'Book Images',
            },
        ),
    ]
